### ISSUE TITLE
to add check if plugin is installed

### ISSUE THREAD

**Issue by Jimmi08** [Jimmi08/jm_jplayer#12]
for menu

**Comment by tgtje** [comment]
something like : 
`if(e107::isInstalled('PLUGIN_FOLDER_NAME'))
{
    echo 'installed';
}
`
or by xml :  dependencies ??

**Comment by Jimmi08** [comment]
yes, this first way, it was just note for future. I haven't time now.  I just noticed that menu is still there after unistall plugin.
