### ISSUE TITLE
idea or wish

### ISSUE THREAD

**Issue by tgtje** [Jimmi08/jm_jplayer#7]
Wouldn't it be better to have separate language locale folders for international use ? (e.g. folder English, folder Czech etc.... (or ability to, as universal use > v2 standarisation)
Needs changes in e107::lan code too..
By patching i can not add a folder, so am asking first.

**Comment by Jimmi08** [comment]
I've added you the access to the folder. No problem, you can do with this plugin you want. I really appreciate your help.
